apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
  ref:
    branch: release-1.37