apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 5m
  path: "https://github.com/kubernetes-sigs/aws-ebs-csi-driver"
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-ebs-csi-driver
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 10m