apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default # Ensure this namespace exists or create it
spec:
  install:
    createNamespace: true
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 15.0.0 # Replace with the desired chart version
  interval: 5m
  releaseName: prometheus
  values:
    alertmanager:
      enabled: true
    server:
      global:
        scrape_interval: 15s
      persistentVolume:
        enabled: true
        storageClass: standard
        size: 8Gi
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
